application: blackchatjack
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /html
  static_dir: html
- url: /game.*
  script: game.py
- url: /stats.*
  script: stats.py
- url: /.*
  script: index.py